spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/exploding_kittens
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret:
    access: VUU3bWZPNVJSS3dzZVZwdGVjVHE2QmFZT1RqaXdrbVF6YzRoelg3S2xVRTZkNTlWUTNpc1J1aUxSZzBrOW4xUHRmWmxGMnNzU09YN09hVE05Y0Z1OTAwR0RnSGladElHSlFnUHNXSVg1TG5TdmlCcUI2UE5rRHZqNzFoeGV1Rjlsam55WnBZdDlRdnk3aGJ2YjVWZVBDNGFtMVJOYzlhY0JoUXZGbkFNZm05cU16TzZuNWprM1F0ZmNhMWNGc2VObHpoTThHeU5mWHhJUGJLZmJaM05ybEZwOVFLTkwwVlFwOG5IbVliZzVjRkttSnlCVk9HRjRpRUxqZllKNkp5UA==
    refresh: cHRiakhLb0ZHR3NXajdCUFk3c2wwbWt5UjhmRHdlMVQ3ZnZ2R0F4Wm55dnJndlBYZ2VZc1oxaFVIakRBTXhLMUdtMUhyd0JFaGladllLNUt4VkNLZkwzWVF2aklCTEtJMnlGSWFYZENDdFVlVXlkUm44RGtiODhicEVvckhmMGN2emtmR3FOVmV4RjQyQ2E1TDNPRW9IMTBWUHZZWFUwd1lDVzhnRVJlYlJvVHFKbDJDOW9hYlhHdVcyQ0JtejZLa3BSNnBRNnpNYTM2emdQWDZ2NGdiNkxvUFBlTno5MVZ5UTZPeHBUak01eDNFUkh5ZFp0eG9sSHRtQkV4UkZYUQ==

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


game.property:
  numOfCardsPlayersHave: 8
  playerStartCards:
    - name: DEFUSE
      quantity: 1
  cardsInGame:
    - name: 'EXPLODING_KITTEN'
      quantity: 4
    - name: 'DEFUSE'
      quantity: 6
    - name: 'ATTACK'
      quantity: 4
    - name: 'FAVOR'
      quantity: 4
    - name: 'NO'
      quantity: 5
    - name: 'GET_LOST'
      quantity: 4
    - name: 'SHUFFLE'
      quantity: 4
    - name: 'SEE_THE_FUTURE'
      quantity: 5
    - name: 'HAIRY_CATATO'
      quantity: 4
    - name: 'TACOCAT'
      quantity: 4
    - name: 'BEARDCAT'
      quantity: 4
    - name: 'NYAN_CAT'
      quantity: 4
    - name: 'CATTERMELON'
      quantity: 4