spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/exploding_kittens
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml